Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -165,10 +165,13 @@ jobs:
         run: |
           echo "CHANGELOG_UPDATED=$(cat changelog_updated.txt)" >> $GITHUB_ENV
       - name: Check if changelog is updated
-        if: env.CODE_CHANGES == 'true' && env.CHANGELOG_UPDATED != 'true'
+        if: env.CODE_CHANGES == 'true'
         run: |
-          echo "Failure: Changelog must be updated for new releases."
-          exit 1
+          if [ "$CHANGELOG_UPDATED" != "true" ]; then
+            echo "Failure: Changelog must be updated for new releases."
+            exit 1
+          fi
+
       
   # Publish to NPM if the event was 'push'.
   # Runs the publish to NPM step only if there were code changes
